### ISSUE TITLE
errors by all modes

### ISSUE THREAD

**Issue by gnilihzeux** [xiaofengsong/IRESfinder#1]
I have set all kinds of parameters combination, but all reports errors.
```
Illegal division by zero at /geneseed/Biosoft/IRESfinder/module/calculate_features.pl line 73, <ID> line 9.
python2.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
warnings.warn(CV_WARNING, FutureWarning)
Traceback (most recent call last):
  File "IRESfinder/IRESfinder.py", line 160, in <module>
    PrintResult(ids,labels,probas[:,1],outfile)
  File "IRESfinder/IRESfinder.py", line 48, in PrintResult
    if labels[i] == 1:
IndexError: index 8 is out of bounds for axis 0 with size 8
```
my tools' information is as follows:
```
Python 2.7.15 :: Anaconda, Inc.
perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi
sklearn 0.20.2
```

**Comment by zhaodoctor** [comment]
These errors may be due to that the sequence you input is shorter than 5. Please check the length of your input sequences. If these errors were still there, please show me your input file, which would be helpful for me to get the wrong reasons.
