### ISSUE TITLE
index

### ISSUE THREAD

**Issue by luhan125** [xiaofengsong/IRESfinder#4]
Hello,

When I used IRESfinder, I have this err:

Illegal division by zero at /asnas/guocx_group/yaofw/software/IRESfinder-master/module/calculate_features.pl line 73, <ID> line 124.
Traceback (most recent call last):
  File "/asnas/guocx_group/yaofw/software/IRESfinder-master/IRESfinder.py", line 160, in <module>
    PrintResult(ids,labels,probas[:,1],outfile) 
  File "/asnas/guocx_group/yaofw/software/IRESfinder-master/IRESfinder.py", line 48, in PrintResult
    if labels[i] == 1:
IndexError: index 123 is out of bounds for axis 0 with size 123

Could you give me some advice to solve this problem?
Thank you very much!

Best,

Lu

**Comment by zhaodoctor** [comment]
This error may be due to that some input sequences are shorter than 5. Please check the length of your input sequences.

**Comment by luhan125** [comment]
Great! Thank you!
