### ISSUE TITLE
Wrong number of columns error

### ISSUE THREAD

**Issue by AustinChiappetta** [xiaofengsong/IRESfinder#7]
Hello, 
I am experiencing the following error when trying to use IRESfinder.py:

`Illegal division by zero at /Users/admin/Data/Computational/IRESfinder-master/module/calculate_features.pl line 73, <ID> line 66.
Traceback (most recent call last):
  File "IRESfinder.py", line 146, in <module>
    data = np.loadtxt(f)
  File "/Users/admin/opt/anaconda3/envs/IRESfinder/lib/python2.7/site-packages/numpy/lib/npyio.py", line 927, in loadtxt
    % line_num)
ValueError: Wrong number of columns at line 66`

Could you give me some advice on how to solve this problem? 
Thank you!

Best,
Austin

**Comment by AustinChiappetta** [comment]
I realized that the error was due to accidentally including improperly formatted sequences because of how I was parsing my upstream data.
