### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by VinylLee** [xiaofengsong/IRESfinder#9]
Traceback (most recent call last):
  File ".\IRESfinder.py", line 150, in <module>
    data = np.loadtxt(f)
  File "D:\Python27\lib\site-packages\numpy\lib\npyio.py", line 1141, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "D:\Python27\lib\site-packages\numpy\lib\npyio.py", line 1065, in read_data
    % line_num)
ValueError: Wrong number of columns at line 9

我运行example，大部分时候报错，有时候可以运行，请问怎么解决

**Comment by sam-israel** [comment]
I have managed to solve this error by running the program on a computer with much more RAM available (32GB minimum, the more the better)
